### PR TITLE
Drop in replacements

### PR DESCRIPTION
**Pull request by Dwood15**
I apologize if this is a little disorganized/eclectic. Still working through how this all fits in with npm. Stripped out a large portion of the original doc I had written after hearing there is a WIP on an rfcs for deep aliasing, and didn't want to duplicate that effort.

This rfcs is about marking a package as being a viable candidate for both aliasing and/or deep-aliasing for another package. 

Should this get accepted, being able to search for packages in lieu of another package, regardless of depth, should become pretty easy.

### CODE REVIEW

**Comment by nickmccurdy** [comment]
This would be great for tracking packages that are renamed in major releases, especially now that packages like `@babel/core` and `@material-ui/core` and moving to organizations. It's confusing when you update the old package names to the latest version and don't realize that you're missing new versions at a different package name.

**Comment by styfle** [comment]
This would be amazing!

The web interface already shows scores for Popularity, Quality, and Maintenance...so adding the ability to compare "Alias Packages for X" in the web interface would be excellent when comparing these aliases 👌 

Something like this (but instead of search on keyword, it would be alias):
https://www.npmjs.com/search?q=keywords:babel

**Comment by zkat** [comment]
After some discussion, we decided that the upcoming overrides API (RFC upcoming, /cc @aeschright) solves this problem without the added complication of registry-side changes.

**Comment by styfle** [comment]
Can you link to the RFC when it’s available so we can follow it?

**Comment by aeschright** [comment]
Here's the overrides RFC: https://github.com/npm/rfcs/pull/27

**Comment by Dwood15** [comment]
@zkat I feel like it's a mistake to not add registry changes that allow searching for overrides

**Comment by hutson** [comment]
The overrides API seems targeted at the consumer to empower them to replace packages in their tree.

However, it does not empower the package maintainer to communicate and encourage consumers to adopt replacement packages (in the case of renames, scope migrations, etc.)

:+1:  on re-opening this RFC please

**Pull request closed without merging**
