### PR TITLE
Secure NPM

### PR DESCRIPTION
**Pull request by wilk**

### CODE REVIEW

**Comment by wilk** [comment]
I tried to link it to the rfc's community forum but I can't do that because I got the following error: "Sorry you cannot post a link to that host."
May I consider this RFC opened?

**Comment by devsnek** [comment]
how does this fix the situation when malicious code runs on a user's computer, like with the most recent worm? in most cases people don't lock down their `git push` any more than they lock down their `npm publish`...

not to say that increased visibility is bad but I think this dodges the actual problem. some form of 2fa on every publish might be a better solution, although I'm sure that isn't a complete solution either.

**Comment by 0fork** [comment]
In my opinion this needs to be merged asap and should be mandatory in any future package updates. It makes no sense that we sacrifice even a small part of the security of all possible end users for the small inconvenience of adding a verification step in the build process that can and should be automated anyway.

**Comment by wilk** [comment]
Another relevant issue for this topic: https://github.com/dominictarr/event-stream/issues/116

**Comment by superlbr** [comment]
why not maintain a blacklist in github

**Comment by kurtextrem** [comment]
@superlbr I don't think that would be the right solution, because you have to find compromised packages first in order to add them to a list. When that is the case, it is too late already (most likely).

**Comment by isiahmeadows** [comment]
@wilk Attacking this is simple: direct npm to a Git branch that conveniently confirms its "integrity", then once you confirm it's published successfully, delete the commit and branch to cover your tracks.

**Comment by superlbr** [comment]
@kurtextrem there should be whitelist also, who is able to granted to maintain such an important repository

**Comment by zkat** [comment]
Hey, thanks for submitting this!

I believe this is a very roundabout way of achieving the sort of thing you'd get when using package signing, and the preferred solution here would be for us to get around to actually implementing and releasing package signing support in the CLI.

There are two significant problems with this proposal that I think are blockers to it moving forward:
1. It assumes git repositories will be existent and available reliably.
2. A large % of packages out there use `files` to selectively publish, and/or they use some sort of transpilation or bundling process, which will make shasums simply not match, or often not match.

As far as the quoted attacks, and other attacks go, this would either not solve it, or there's other, better solutions for the same attack, such as two-factor authentication and package signing.

We've decided we're going to continue to proceed in that direction, and so we'll be closing this PR. Thank you so much again for taking the time to write this and submit it, and thanks a bunch for everyone involved in the conversation. Keep an eye out for package signing! It's on our roadmap, as are other security features coming in 2019. Making sure the registry is safe to use is a very high priority for us, as is making sure that security doesn't compromise the quality of user experience our userbase has come to expect from npm.

**Pull request closed without merging**
