### PR TITLE
Publish older versions without a tag

### PR DESCRIPTION
**Pull request by watson**

### CODE REVIEW

**Comment by ljharb** [comment]
This would be great; i currently use https://npmjs.com/safe-publish-latest to prevent accidentally publishing a backport as “latest”.

Even better (on top of this) would be if the tag could be overwritten in prepublish - then i could have a package that removed the “latest” tag when it was unsafe.

**Comment by ljharb** [comment]
@evocateur that’s a great workaround, but it still ends up creating a tag that i have to remove after publishing.

**Comment by evocateur** [comment]
@ljharb Oh, fair enough. At least it wouldn't be "latest" by default in the scenario I described. Still doesn't avoid a tag altogether, you are correct.

**Comment by ljharb** [comment]
@zkat couldn’t something like `--no-tag` be added as a semver-minor, and the breaking change later be making that the default?

**Comment by ljharb** [comment]
Oh sure, maybe `--without-tag` then - bikeshed aside it seems totally doable as a semver-minor

**Pull request merged**
