### PR TITLE
Stop storing `integrity` for git dependencies

### PR DESCRIPTION
**Pull request by nlf**
This is relevant for
 - npm/cli#2846
 - npm/cli#2971

### CODE REVIEW

**Comment by ljharb** [comment]
Would there be value in storing the git sha, since the URL might not contain it?

**Comment by nlf** [comment]
> Would there be value in storing the git sha, since the URL might not contain it?

the sha is already what gets stored in the `resolved` field today

**Comment by bnb** [comment]
will restate what I said in the meeting, half in jest but also half seriously: if this feature isn't working in a consistent way that accomplishes what it says it does, entirely removing it is imo potentially a candidate for a patch release.

**Comment by derTobsch** [comment]
We run into the same problem today and now our ci pipline is stuck, because it does calculate a different hash than any other development machine. If we can help to test this issue, please let us know.

**Comment by nlf** [comment]
npm@8.5.2 no longer compares the stored integrity field to the generated data

**Pull request merged**
